# Generated by Django 2.1.1 on 2018-10-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=50)),
                ('contact_no', models.CharField(max_length=11)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
